#!/bin/sh

SIZE=""
OPTS=""
FGCOL=0
BGCOL=0

if [ -z $1 ]; then
	echo "[WARN] No b/f specified - generating random foreground color"
	FGCOL=$(( ( RANDOM % 256 ) ))
	OPTS="-f $FGCOL"
else
	BG=$(echo $1 | grep -o -P 'b')
	if [ $BG ]; then
		echo "[ECHO] Generating random background color..."
		BGCOL=$(( ( RANDOM % 256 ) ))
		OPTS="-b $BGCOL"
		FG=$(echo $1 | grep -o -P 'f')
		if [ $FG ]; then
			echo "[ECHO] Generating random foreground color..."
			FGCOL=$(( ( RANDOM % 256 ) ))
			OPTS="$OPTS -f $FGCOL"
		fi
	else
		echo "[ECHO] Generating random foreground color..."
		FGCOL=$(( ( RANDOM % 256 ) ))
		OPTS="-f $FGCOL"
	fi
fi

if [ -z $2 ]; then
	SIZE="1"
else
	SIZE="$2"
fi

OPTS="$OPTS -s $SIZE"
echo $OPTS
/bin/hasklock $OPTS

